In [1]:
import numpy as np
import pandas as pd

In [2]:
A = np.array([
    [1,3,2],
    [4,2,-1],
    [5,5,1]
])

a,av=np.linalg.eig(A)
a,av


(array([ 6.0000000e+00, -2.0000000e+00,  1.1293683e-15]),
 array([[ 5.05076272e-01,  7.07106781e-01,  4.61566331e-01],
        [ 3.03045763e-01, -7.07106781e-01, -5.93442426e-01],
        [ 8.08122036e-01, -5.16701183e-16,  6.59380473e-01]]))

In [3]:
from sympy import Matrix, pprint

A_sym = Matrix([
    [1, 3, 2],
    [4, 2, -1],
    [5, 5, 1]
])

for val, mult, vecs in A_sym.eigenvects():
    print(f"λ = {val}, multiplicidad = {mult}")
    for v in vecs:
        pprint(v)

A_sym.eigenvects()

λ = -2, multiplicidad = 1
⎡-1⎤
⎢  ⎥
⎢1 ⎥
⎢  ⎥
⎣0 ⎦
λ = 0, multiplicidad = 1
⎡7/10 ⎤
⎢     ⎥
⎢-9/10⎥
⎢     ⎥
⎣  1  ⎦
λ = 6, multiplicidad = 1
⎡5/8⎤
⎢   ⎥
⎢3/8⎥
⎢   ⎥
⎣ 1 ⎦


[(-2,
  1,
  [Matrix([
   [-1],
   [ 1],
   [ 0]])]),
 (0,
  1,
  [Matrix([
   [ 7/10],
   [-9/10],
   [    1]])]),
 (6,
  1,
  [Matrix([
   [5/8],
   [3/8],
   [  1]])])]

In [4]:
from sympy import Matrix

B = Matrix([
    [4, 2, 2],
    [-2,-1,-4],
    [0, 0, 3]
])

for val, mult, vecs in B.eigenvects():
    dim_autoespacio = len(vecs)
    print(f"λ={val}  multiplicidad algebraica={mult}  multiplicidad geométrica={dim_autoespacio}")
    for v in vecs:
        print(f"  {v.T}")

λ=0  multiplicidad algebraica=1  multiplicidad geométrica=1
  Matrix([[-1/2, 1, 0]])
λ=3  multiplicidad algebraica=2  multiplicidad geométrica=2
  Matrix([[-2, 1, 0]])
  Matrix([[-2, 0, 1]])


In [5]:
[]

[]

In [9]:
A = np.array([
    [1,2,-1,0],
    [2,3,1,6],
    [0,1,0,1]
])
np.linalg.svdvals(A)

array([7.26324773, 2.23310342, 0.50841079])