In [1]:
import numpy as np
def prod(x,y):
    return 5*x[0]*y[0]+x[0]*y[1]+x[1]*y[0]+3*x[1]*y[1]

x=np.array([0,1])
y=np.array([1,0])
z=np.array([1,1])

prod(x+y,z),(prod(x,z)+prod(y,z))

(10, 10)

In [12]:
vectors =[ np.array((1,2,1)), np.array((3,0,-1)), np.array((-1,2,-3))] 

def proyeccion_ortogonal(u,v):
    num = np.dot(u,v)
    den = np.dot(u,u)
    return (num/den) * u
def gram_schmitt(vectors):
    ret = []
    for i in range(len(vectors)):
        if not ret:
            ret.append(vectors[i])
            continue
        ret.append(vectors[i] - proyeccion_ortogonal(vectors[i-1], vectors[i]))
    return [v* (1/np.linalg.norm(v)) for v in ret]
print(proyeccion_ortogonal(vectors[0], vectors[1]))
gram_schmitt(vectors)


[0.33333333 0.66666667 0.33333333]


[array([0.40824829, 0.81649658, 0.40824829]),
 array([ 0.87287156, -0.21821789, -0.43643578]),
 array([-0.26726124,  0.53452248, -0.80178373])]

In [21]:
x = np.array([[1],[1]])
##No es simetrica
A = np.array([
    [1,5],
    [3,-2]
])



In [ ]:
#es simetrica...pero no cumple la condicion de que ningun vector que no sea 0 lo anule
x = np.array([[2 + np.sqrt(2)],[1]])
A = np.array([
    [1,-2],
    [-2,2]
])
x.T @ A @x


array([[0.]])